# Generated by Django 4.2.1 on 2023-06-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsAPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=8000, unique=True)),
                ('image', models.ImageField(upload_to='posters/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
