# Generated by Django 4.2.1 on 2023-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogsapimodel',
            index=models.Index(fields=['title'], name='blogs_blogs_title_7a2f53_idx'),
        ),
    ]
