# Generated by Django 4.2.1 on 2023-06-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
