# Generated by Django 4.2.1 on 2023-06-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_categorymodel_blogsapimodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsapimodel',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.categorymodel', to_field='category'),
        ),
    ]
