# Generated by Django 4.2.1 on 2023-06-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blogsapimodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsapimodel',
            name='category',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='blogs.categorymodel', to_field='category'),
        ),
    ]
